name: 自动提交

on:
  schedule:
    - cron: '0 */4 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-git@v2
      - run: |
        git add file cron.sh
        git commit -m "自动提交"
        git push origin master
